// <auto-generated />
using System;
using CoffeeShop.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Migrations
{
    [DbContext(typeof(CoffeeDbContext))]
    partial class CoffeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Entities.GroupBasket.BasketItem", b =>
                {
                    b.Property<int>("BasketItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketItemId"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("CoffeeItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BasketItemId");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBasket.BuyerBasket", b =>
                {
                    b.Property<int>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.HasKey("BasketId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBuyer.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AddressId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBuyer.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerId"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserGuid")
                        .HasColumnType("varchar(40)");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyer");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupItem.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<bool>("AvailableStatus")
                        .HasColumnType("bit");

                    b.Property<int>("CoffeeItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RestockDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("CoffeeItemId")
                        .IsUnique();

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupItem.CoffeeItem", b =>
                {
                    b.Property<int>("CoffeeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoffeeItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CoffeeItemId");

                    b.ToTable("CoffeeItems");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupItem.Customization", b =>
                {
                    b.Property<int>("CustomizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizationId"));

                    b.Property<int>("CoffeeItemId")
                        .HasColumnType("int");

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilkType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugarLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Topping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomizationId");

                    b.HasIndex("CoffeeItemId")
                        .IsUnique();

                    b.ToTable("Customization");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupOrder.BuyerOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupOrder.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBasket.BasketItem", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupBasket.BuyerBasket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBasket.BuyerBasket", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupBuyer.Buyer", "Buyer")
                        .WithMany("Baskets")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBuyer.Address", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupBuyer.Buyer", "Buyer")
                        .WithMany("Address")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupItem.Availability", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupItem.CoffeeItem", "CoffeeItem")
                        .WithOne("Availability")
                        .HasForeignKey("CoffeeShop.Entities.GroupItem.Availability", "CoffeeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeItem");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupItem.Customization", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupItem.CoffeeItem", "CoffeeItem")
                        .WithOne("Customization")
                        .HasForeignKey("CoffeeShop.Entities.GroupItem.Customization", "CoffeeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeItem");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupOrder.BuyerOrder", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupBuyer.Buyer", "Buyer")
                        .WithMany("Order")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoffeeShop.Entities.GroupOrder.OrderAddress", "ShipAddress", b1 =>
                        {
                            b1.Property<int>("BuyerOrderOrderId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("BuyerOrderOrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("BuyerOrderOrderId");
                        });

                    b.OwnsOne("CoffeeShop.Entities.GroupOrder.OrderStatus", "Status", b1 =>
                        {
                            b1.Property<int>("BuyerOrderOrderId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CompleteTime")
                                .HasColumnType("datetime");

                            b1.Property<DateTime>("LastUpdate")
                                .HasColumnType("datetime");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("BuyerOrderOrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("BuyerOrderOrderId");
                        });

                    b.Navigation("Buyer");

                    b.Navigation("ShipAddress")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupOrder.OrderItem", b =>
                {
                    b.HasOne("CoffeeShop.Entities.GroupOrder.BuyerOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoffeeShop.Entities.GroupOrder.ItemOrdered", "Item", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("int");

                            b1.Property<int>("CoffeeItemId")
                                .HasColumnType("int");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PictureUri")
                                .IsRequired()
                                .HasColumnType("nvarchar(265)");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Item")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBasket.BuyerBasket", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupBuyer.Buyer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Baskets");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupItem.CoffeeItem", b =>
                {
                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("Customization")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeShop.Entities.GroupOrder.BuyerOrder", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
